### ISSUE TITLE
Docker: docker-compose build - "no basic auth credentials"

### ISSUE THREAD

**Issue by FMGordillo** [IBM-Bluemix/bluechatter#11]
I was following the tutorial for Docker [until here](https://github.com/IBM-Bluemix/bluechatter#2_2-build--run-container-locally) and when i put `docker-compose build` in my PowerShell terminal, i got this:

![image](https://user-images.githubusercontent.com/7970174/28252624-e1153992-6a6c-11e7-901a-01af025e8147.png)

Thanks in advance

**Comment by wangzhidong** [comment]
I met same issue, how to resovle it?

**Comment by Twanawebtech** [comment]
The repo has been updated, if you are still having this issue then please reopen this issue. 
Thanks.
