### ISSUE TITLE
image ibmnode:latest not found - docker build and pull failing

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Bluemix/bluechatter#9]
While checking this sample, I had an hard stop with the below error. Even _docker pull i_s failing with the same error.
> Sending build context to Docker daemon 12.14 MB
> Step 1/8 : FROM registry.ng.bluemix.net/ibmnode:latest
> Pulling repository registry.ng.bluemix.net/ibmnode
> Error: image ibmnode:latest not found

**Comment by Twanawebtech** [comment]
@VidyasagarMSC you still having issues? 
Please close the issue if you are sorted.
